### ISSUE TITLE
Dockerfile Build error

### ISSUE THREAD

**Issue by garyluu** [ICGC-TCGA-PanCancer/dkfz_dockered_workflows#11]
Dockerfile on develop does not build:

A build step failed: The command '/bin/sh -c wget --quiet https://s3.amazonaws.com/pan-cancer-data/workflow-data/DKFZPancancer/Roddy_2.2.49_COW_1.0.132-1_CNE_1.0.189.tar.gz && tar zxf Roddy_2.2.49_COW_1.0.132-1_CNE_1.0.189.tar.gz && mv Roddy /roddy/bin/' returned a non-zero code: 8

**Comment by denis-yuen** [comment]
To be clear, this is probably just that the aws file is now missing. 
The solution, is that this means the file should be on icgc-portal or similar

**Comment by junjun-zhang** [comment]
If it's reference data file, it could be put here: https://dcc.icgc.org/releases/PCAWG/reference_data/pcawg-dkfz.

It seems it's the binary for Roddy. Before moving to S3, where was it stored? I remember some workflow binaries were kept in GNOS, was it the case for Roddy? If the copy on AWS S3 is gone, where can we find an exact copy of it?

@briandoconnor do you know?

**Comment by denis-yuen** [comment]
@junjun-zhang  It is probably easiest to download an older Docker image and get it from there.

**Comment by junjun-zhang** [comment]
That's a good idea. Thanks @denis-yuen. Can you please verify again this is indeed open access?

**Comment by denis-yuen** [comment]
@junjun-zhang  I'm not aware as to the licensing for Roddy. 
I think this would probably be a question for @dankwart-de or someone on that team

**Comment by junjun-zhang** [comment]
I believe this has been resolved.
