### ISSUE TITLE
Any feel for how long it takes this workflow to process the bams from a single donor?

### ISSUE THREAD

**Issue by mdperry** [ICGC-TCGA-PanCancer/dkfz_dockered_workflows#6]
Hi,

I was able to get the pcawg-delly-workflow to run from its dockstore docker image (using the uniformly aligned WGS bam files from a PCAWG donor), but thus far I have not been able to get this dkfz-roddy workflow to run: https://dockstore.org/containers/quay.io/pancancer/pcawg-dkfz-workflow.  I understand that as currently configured, the dockstore client is not launching the jobs, and I have obtained the dependencies tarball file that was stored in a GNOS repository.  I am running this on AWS using a single c3.8xlarge EC2 instance, so it has 32 CPU, 60G of RAM, and 640G of SSD Hard disk space.

It seems like the job just hangs, it launches the three individual steps, cnvCalling, snvCalling, and indelCalling, in fairly short order (according to the docker logs), but then the STDERR (and log) just spits out 'Waiting for jobs to finish'.  Every 5 minutes it prints the same message in triplicate, for several days, and I have never found any indication that it is writing output anywhere.  Right now I am putting together a detailed timeline, but it seems like the last process that launched (based on the logs that the roddy process itself generates) is indelAnnotation.  I infer that all three of those different steps are still running, hence the triplicate STDERR messages, but I don't have a way to tell (yet) if this behaviour is normal, and it just takes a long time, particularly on a machine configured this way, or if it is stuck in an infinite loop.

Any help or suggestions would be appreciated.

Thanks,

-- Marc Perry

**Comment by denis-yuen** [comment]
@christinayung might have a handle on this , personally I've been trying to get this to run with  cwl 1.0, but I haven't managed to run to completion yet so I'm interested too.

Edited: 
Ok, so we've compared notes. On average, the whole DKFZ/EMBL workflow supposed to take 2 days with 16 cores and 64GB of memory on AWS, but it can be dependent on the data taking +/- a day. However, this is only the DKFZ portion of it, so it should be some fraction of the 2 days

**Comment by mdperry** [comment]
I was eventually able to get this docker image to run successfully on one PCAWG WGS dataset, however there were several modifications that were required in my hands.  I was using a single c3.8xlarge instance, which as I recall has 32 VCPU, 60G of RAM and 600+ G of SSD storage.
One of the first things that I noticed was that in the GitHub README.md describing how to build this docker image there are explicit instructions on how to modify two of the Application.ini files.  Inside the running docker container I found these files located in /roddy/bin/Roddy/.  But they had not been modified.   So I now routinely make that change whenever I launch a new container (I don't actually know if it makes a difference, but since I had so many other issues I did not want to take the time to test this hypothesis).  My assumption is that whomever created the current docker image did not run the command to swap /root/roddy/, but that is a guess.

A second issue is that the default configuration for Sun Grid Engine inside the running container (at least in the VMs that I have been using on AWS) sets one of the complex_variables named s_data at ~ 3.75G.  This means that some of the ~ 69 SGE jobs that get queued up never leave the 'pending' state, because, if I understand correctly, they are limited by the fact that no resources are available with more than 3.75G of RAM.  Reviewing the list of qsub jobs reveals many that require more than this amount of RAM--some as much as 51G or 56G(!).  To circumvent this I figured out how to modify the amount of s_data setting (I now pick 120G). This has the immediate effect of starting to run some of the pending jobs.  Eventually they all finish.

The final problem I encountered was that the directory named /mnt/datastore/resultdata/ never gets made (I assume this command used to be in the script named runwrapper.sh), and so the job fails because none of the files can be written/copied into there.  So now I routinely create that directory, and also /mnt/datastore/resultdata/data/ manually before I launch the perl script on the command line in /var/spool/cwl/.

Do you know if anyone has used roddy to analyze WXS datasets?

**Comment by denis-yuen** [comment]
I can verify your findings. 

I ran into the resultdata and application.ini issues. Those should be fixed in 2.0.0_cwl1.0
I didn't run into the SGE issue, ran into a different one since cwltool locks down the hostname away from "master", and ended up replacing much of that.
